version: "3.8"
services:
    mysqldb:
      image: 'mysql'
      #ports:
        #- '3307:3306'
      #volumes:
      #  - data:/data/db
      environment: 
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: post_db
      container_name: post-app-db
      healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-ppass"]
        interval: 5s
        timeout: 5s
        retries: 20

    post-api:
      build: ./post-api
      container_name: post-app-api
      ports:
        - '8080:8080'
      #volumes:
      #  - ./logs:/app/logs
      #  - ./backend:/app
      #  - /app/node_modules
      depends_on:
        mysqldb:
          condition: service_healthy
      #links:
        #- mysqldb
      #image: 'goals-node'
      #build:
      #  context: ./backend
      #  dockerfile: Dockerfile
      #  args:

    #post-view:
      #build: ./post-view